# Generated by Django 5.2.6 on 2025-09-19 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='lessons/covers/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='resource_file',
            field=models.FileField(blank=True, null=True, upload_to='lessons/resources/'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Optional embedded video URL (YouTube, etc.)'),
        ),
    ]
